name: "Quality Contributions"
on:
  issues:


jobs:
  # Check if the PR is for quality contributions; all other jobs depend on this one.
  check:
    name: Is Quality Contribution?
    runs-on: ubuntu-latest
    steps:
      - id: title
        run: |
          echo "Checking pull request with title ${{ github.event.pull_request.title }} from source branch ${{ github.event.pull_request.head.ref }}"
          if ! [[ "${{ github.event.pull_request.title }}" =~ ^AIRO-[0-9]+[[:space:]].*$ ]] && ! [[ "${{ github.event.pull_request.head.ref }}" =~ ^AIRO-[0-9]+.*$ ]]
          then
            echo -e "Please make sure one of the following is true:\n \
            1. the pull request title starts with 'AIRO-xxxx ', e.g. 'AIRO-1024 My
