name: "Quality Contributions"
on:
  pull_request:

defaults:
  run:
    shell: pwsh

jobs:
  # Check if the PR is for quality contributions; all other jobs depend on this one.
  check:
    name: Is Quality Contribution?
    runs-on: ubuntu-latest
    steps:
      - id: title
        run: |
          $Check = "${{ contains(github.event.pull_request.title, 'Quality:') }}"
          "Check: $Check"
          "check=$Check" >> $env:GITHUB_OUTPUT
