name: "Quality Contributions"
on:
  pull_request:


jobs:
  # Check if the PR is for quality contributions; all other jobs depend on this one.
  check:
    name: Is Quality Contribution?
    runs-on: ubuntu-latest
    steps:
      - id: title
        run: |
          if [[ "${{ github.event.pull_request.title }}" =~ ^(feat|fix|chore|build|ci|docs|style|refactor|perf|test)(\([-a-zA-Z0-9,]+\))?\!?\: ]]; then
              echo pass
          else
              echo "PR title does not match conventions"
              echo "PR title: ${{ github.event.pull_request.title }}"
              exit 1
          fi
